# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb0716f7564cc4ba30d6771f520b1d88df4011951a9e8a9763186df37dd733f7e8489295c40fb8b7c6973b1a3df9134ce8c23a8890bc47ac3d2cc4cc47c87cc

test:
  secret_key_base: c9291f998f39bda110b93f8e2f1497a797fa0216c49c68572d8ffb0b814e7e1fb2ca75dd23bf2977cdecc2c822389516911263d0ca2f705ad4659594e0a451bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
